### ISSUE TITLE
Modal background staying grey when back button is pressed

### ISSUE THREAD

**Issue by wil93** [olimpiadi-informatica/cmsocial#24]
as reported here https://forum.cms.di.unipi.it/t/confusione-di-alcuni-tag-e-piccolo-bug/4523

**Comment by lucach** [comment]
Calling `$('.modal-backdrop').remove();` when `window.popstate` [1] is fired should suffice to solve this.

[1] = https://developer.mozilla.org/it/docs/Web/Events/popstate
